### ISSUE TITLE
Unicode error during 'kegbot upgrade'

### ISSUE THREAD

**Issue by bh651** [Kegbot/kegbot-server#328]
Does anyone know how I can get past this error?

(kb)kegbot@kegbot-server:~/.kegbot$ kegbot upgrade
Upgrading from 1.0.2 to 1.1.1
--- Running command: syncdb --noinput -v 0
--- Running command: migrate -v 0
--- Running command: regen_stats
Traceback (most recent call last):+++++++++++++++++++++++++++++          ] 710/924
  File "/home/kegbot/kb/bin/kegbot", line 39, in <module>
    management.execute_from_command_line()
  File "/home/kegbot/kb/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/kegbot/kb/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/kegbot/kb/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/kegbot/kb/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/kegbot/kb/local/lib/python2.7/site-packages/pykeg/core/management/commands/upgrade.py", line 95, in handle
    run(regen_stats.Command())
  File "/home/kegbot/kb/local/lib/python2.7/site-packages/pykeg/core/management/commands/upgrade.py", line 46, in run
    cmd.run_from_argv([sys.argv[0], cmdname] + args)
  File "/home/kegbot/kb/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/kegbot/kb/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/kegbot/kb/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/kegbot/kb/local/lib/python2.7/site-packages/pykeg/core/management/commands/regen_stats.py", line 42, in handle
    stats.rebuild_from_id(0, cb=cb)
  File "/home/kegbot/kb/local/lib/python2.7/site-packages/pykeg/core/stats.py", line 223, in rebuild_from_id
    _build_all_views(drink, results_cache=results_cache)
  File "/home/kegbot/kb/local/lib/python2.7/site-packages/pykeg/core/stats.py", line 292, in _build_all_views
    stats = _build_single_view(drink, view, prior_stats=prior_stats)
  File "/home/kegbot/kb/local/lib/python2.7/site-packages/pykeg/core/stats.py", line 238, in _build_single_view
    logger.debug('>>> Building stats for {}'.format(view))
  File "/home/kegbot/kb/local/lib/python2.7/site-packages/pykeg/core/stats.py", line 44, in __str__
    ret += 'user={} '.format(self.user.username)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 2: ordinal not in range(128)

**Comment by mik3y** [comment]
Fix in v1.2.2
