### ISSUE TITLE
Posting pour to kegbot server failed due to bad user name.

### ISSUE THREAD

**Issue by brobzilla** [Kegbot/kegbot-server#336]
Just implemented our system and every user had succesful pours except for a user who had a .(period) in his user name (i.e. first.last).  This happened with both of his pours.  I wasn't sure if the android app messed up the name or if the server didn't' allow the user name with period.

```
May 20, 2015, 1:30 a.m. (pykeg.web.api.util) BadRequestError: {'username': [u'Enter a valid value.']}
Traceback (most recent call last):
  File "/data/kb/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/kb/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/data/kb/local/lib/python2.7/site-packages/pykeg/web/api/views.py", line 537, in tap_detail
    return _tap_detail_post(request, tap)
  File "/data/kb/local/lib/python2.7/site-packages/pykeg/web/api/views.py", line 60, in wrapped_view
    return view_func(*args, **kwargs)
  File "/data/kb/local/lib/python2.7/site-packages/pykeg/web/api/views.py", line 648, in _tap_detail_post
    raise kbapi.BadRequestError, _form_errors(form)
BadRequestError: {'username': [u'Enter a valid value.']}
```

**Comment by mik3y** [comment]
Stale issue - but this is now fixed! Cheers.
